fix app title
enjin/platform-ui pull request #43
Opened 2023-10-24 07:39 UTC by zlayine

2023-10-24 08:58 UTC, v16Studios requested changes

2023-10-24 09:28 UTC, zlayine commented on resources/js/components/App.vue
> +})();
good idea! i have added now the APP_NAME as title for hosted platform

2023-10-30 17:22 UTC, leonardocustodio approved these changes

2023-10-31 09:24 UTC, v16Studios approved these changes

2023-10-31 09:25 UTC, merged